# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=16.0.0
group=com.texelsaur.minecraft.storagedrawersextra
java_version=21

# Common
minecraft_version=1.21.5
mod_name=Storage Drawers Extra Reloaded
mod_author=Texelsaur, BONNe
mod_id=storagedrawersextrareloaded
file_name=storage-drawers-extra-reloaded
license=MIT
credits=
description=Additional wood variants for Storage Drawers
minecraft_version_range=[1.21, 1.22)
neo_form_version=1.21.5-20250325.162830

storagedrawers_range=[16, 17)

# Fabric
fabric_version=0.128.2+1.21.5
fabric_loader_version=0.18.4

fabric_storagedrawers=6714385
fabric_jei=7181663

fabric_biomesoplenty=6602038
fabric_glitchcore=6398450
fabric_terrablender=6465682

night_config=3.6.4
typetools=0.6.3

fabric_ohthebiomeswevegone=7386767
fabric_ohthetreesyoullgrow=6607551
fabric_corgilib=6850554
fabric_geckolib=6622736

fabric_ecologics=6751318
fabric_cloth_config=5729125

# Forge
forge_version=55.1.4
forge_loader_version_range=[54,)

forge_storagedrawers=6714388
forge_jei=7181664

forge_biomesoplenty=6602036
forge_glitchcore=6398448
forge_terrablender=6465680

forge_ohthebiomeswevegone=7386771
forge_ohthetreesyoullgrow=6607552
forge_corgilib=6850555
forge_geckolib=6622738

# NeoForge
neoforge_version=21.5.96
neoforge_loader_version_range=[4,)

neoforge_storagedrawers=6714394
neoforge_jei=6767951

neoforge_biomesoplenty=6602037
neoforge_glitchcore=6398449
neoforge_terrablender=6465681

neoforge_ohthebiomeswevegone=7386772
neoforge_ohthetreesyoullgrow=6607553
neoforge_corgilib=6850558
neoforge_geckolib=6622742

neoforge_immersive_engineering=6733669

neoforge_autumnity=7118591
neoforge_blueprint=7148094
neoforge_gallery=6449910

neoforge_ecologics=6751339

neoforge_upgrade_aquatic=7115763