# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=20.0.0
group=com.texelsaur.minecraft.storagedrawersextra
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Storage Drawers Extra Reloaded
mod_author=Texelsaur, BONNe
mod_id=storagedrawersextrareloaded
file_name=storage-drawers-extra-reloaded
license=MIT
credits=
description=Additional wood variants for Storage Drawers
minecraft_version_range=[1.21.11, 1.22)
neo_form_version=1.21.11-20251209.172050

storagedrawers_range=[20, 21)

# Fabric
fabric_version=0.141.1+1.21.11
fabric_loader_version=0.18.4

fabric_storagedrawers=7352799
fabric_jei=7428956

fabric_biomesoplenty=7454390
fabric_glitchcore=7335722
fabric_terrablender=7326874

night_config=3.6.4
typetools=0.6.3

fabric_ohthebiomeswevegone=7386824
fabric_ohthetreesyoullgrow=7363759
fabric_corgilib=7386250
fabric_geckolib=7447708

fabric_ecologics=6751318
fabric_cloth_config=5729125

# Forge
forge_version=61.0.1
forge_loader_version_range=[61,)

forge_storagedrawers=7335079
forge_jei=7391660

forge_biomesoplenty=7454387
forge_glitchcore=7335720
forge_terrablender=7326871

forge_ohthebiomeswevegone=7386825
forge_ohthetreesyoullgrow=7363817
forge_corgilib=7386251
forge_geckolib=7447713

# NeoForge
neoforge_version=21.11.24-beta
neoforge_loader_version_range=[4,)

neoforge_storagedrawers=7335085
neoforge_jei=7428957

neoforge_biomesoplenty=7454388
neoforge_glitchcore=7335721
neoforge_terrablender=7326873

neoforge_ohthebiomeswevegone=7386826
neoforge_ohthetreesyoullgrow=7363818
neoforge_corgilib=7386252
neoforge_geckolib=7447716

neoforge_immersive_engineering=6733669

neoforge_autumnity=7118591
neoforge_blueprint=7148094
neoforge_gallery=6449910

neoforge_ecologics=6751339

neoforge_upgrade_aquatic=7115763