plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'com.matthewprenger.cursegradle' version '1.4.0'
}

neoForge {
    version = neoforge_version

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
            gameDirectory = project.getLayout().getProjectDirectory().dir("run/${it.name}")
        }
        client {
            client()
        }
        dataServer {
            programArgument("--server")
            programArgument("--mod")
            programArgument(mod_id)
            programArgument("--output")
            programArgument(file('src/generated/server/').getAbsolutePath())
            programArgument("--existing")
            programArgument(file('src/main/resources/').getAbsolutePath())
            serverData()
        }
        dataClient {
            programArgument("--client")
            programArgument("--mod")
            programArgument(mod_id)
            programArgument("--output")
            programArgument(file('src/generated/client/').getAbsolutePath())
            programArgument("--existing")
            programArgument(file('src/main/resources/').getAbsolutePath())
            clientData()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}


dependencies {
    implementation "curse.maven:storagedrawers-223852:${neoforge_storagedrawers}"

    implementation "curse.maven:biomes-o-plenty-220318:${neoforge_biomesoplenty}"
    implementation "curse.maven:glitchcore-955399:${neoforge_glitchcore}"
    implementation "curse.maven:terrablender-neoforge-940057:${neoforge_terrablender}"

    implementation "curse.maven:oh-the-biomes-weve-gone-1070751:${neoforge_ohthebiomeswevegone}"
    implementation "curse.maven:oh-the-trees-youll-grow-962544:${neoforge_ohthetreesyoullgrow}"
    implementation "curse.maven:corgilib-693313:${neoforge_corgilib}"
    implementation "curse.maven:geckolib-388172:${neoforge_geckolib}"

//    implementation "curse.maven:immersive-engineering-231951:${neoforge_immersive_engineering}"

//    implementation "curse.maven:autumnity-365045:${neoforge_autumnity}"
//    implementation "curse.maven:blueprint-382216:${neoforge_blueprint}"
//    implementation "curse.maven:gallery-1173553:${neoforge_gallery}"

//    implementation "curse.maven:ecologics-570463:${neoforge_ecologics}"

//    implementation "curse.maven:upgrade-aquatic-326895:${neoforge_upgrade_aquatic}"

    implementation "curse.maven:jei-238222:${neoforge_jei}"
}

sourceSets {
    main {
        resources {
            srcDir 'src/generated/client'
            srcDir 'src/generated/server'
        }
    }
}

curseforge {
    project {
        apiKey = System.getenv("CURSEFORGE_TOKEN")
        id = "1379706"
        changelog = rootProject.file("CHANGELOG_LATEST.md").text
        changelogType = "markdown"
        releaseType = "release"
        addGameVersion "1.21.11"
        addGameVersion "NeoForge"
        addGameVersion "Java 21"

        relations {
            requiredDependency "storage-drawers"
            optionalDependency "oh-the-biomes-weve-gone"
            optionalDependency "biomes-o-plenty"
//            optionalDependency "ecologics"
//            optionalDependency "immersive-engineering"
//            optionalDependency "autumnity"
//            optionalDependency "upgrade-aquatic"
        }
        mainArtifact(tasks.named("jar").flatMap { it.archiveFile }) {
            displayName = "${file_name}-${project.name}-${minecraft_version}-${version}"
        }
        options {
            javaVersionAutoDetect = false
        }
    }
}